<h1>Books</h1>

<hr>

<div class="row">
    
    <?php foreach ($books as $book) : ?>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail book-item">
          <img src="https://i.ytimg.com/vi/prALrHUJ8Ns/hqdefault.jpg" alt="">
          <div class="caption">
            <h3><?=$book->getTitle();?></h3>
            <p><?=$book->getDescription();?></p>
            <p>
                <a href="#" class="btn btn-primary" role="button">Details</a> 
                <a href="#" class="btn btn-default" role="button">Add to cart</a>
            </p>
          </div>
        </div>
      </div>
    <?php endforeach ?>
    
</div>
