<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MVC</title>
    <link rel="stylesheet" href="/css/style.css" type="text/css" />
</head>
<body>
    <a href="/">Home</a>
    <a href="/index.php?route=book/index">Books</a>
    <a href="/index.php?route=default/feedback">Feedback</a>
    
    <hr>
    
    <div>
        <?=\Library\Session::getFlash()?>
    </div>
    
    <?=$content ?>
    
    <hr>
    
    Copyright &copy; 2017
    
</body>
</html>